spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mydatabase
    username: myuser
    password: secret
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  servlet:
    context-path: '/api'
  port: 8080
